In [4]:
import torch
import numpy as np

## Tensor Initialization

In [5]:
# From data
data = [[23,654],[345.4,31.4643]]
torch_data = torch.tensor(data)
torch_data

tensor([[ 23.0000, 654.0000],
        [345.4000,  31.4643]])

In [6]:
# From a Numpy array
np_array = np.array(data)
torch_np = torch.tensor(np_array)
torch_np

tensor([[ 23.0000, 654.0000],
        [345.4000,  31.4643]], dtype=torch.float64)

In [7]:
# From another torch
torch_ones = torch.ones_like(torch_data)
torch_ones

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch_rand = torch.rand_like(torch_data, dtype=torch.float)
torch_rand

tensor([[0.7578, 0.1298],
        [0.9782, 0.4572]])

In [9]:
# Tensor Attributes
tensor = torch.rand(4,5)

print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([4, 5])
Datatype: torch.float32
Device: cpu


In [10]:
# Wait, did I forget to switch to GPU?

print(torch.cuda.is_available())

True


In [23]:
device = torch.device('cuda')

In [24]:
# Tensor Attributes
tensor = torch.rand(4,5)

print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([4, 5])
Datatype: torch.float32
Device: cpu


In [25]:
# Still on CPU
tensor = tensor.to(device)

In [26]:
print(f"Device: {tensor.device}")

Device: cuda:0


In [27]:
# I learned something..

### Indexing

In [28]:
tensor = torch.rand(4,5)
tensor[:1] = 99 #First row only
tensor

tensor([[9.9000e+01, 9.9000e+01, 9.9000e+01, 9.9000e+01, 9.9000e+01],
        [7.4329e-01, 8.3839e-01, 7.0827e-01, 1.2148e-01, 6.5507e-01],
        [2.0483e-01, 8.5266e-01, 5.6404e-01, 5.0472e-01, 7.9405e-02],
        [3.6233e-01, 8.8175e-01, 6.5552e-01, 2.9521e-02, 6.6255e-01]])

In [29]:
# Joining Operation
concatenated = torch.cat([tensor, tensor], dim=1)
concatenated

tensor([[9.9000e+01, 9.9000e+01, 9.9000e+01, 9.9000e+01, 9.9000e+01, 9.9000e+01,
         9.9000e+01, 9.9000e+01, 9.9000e+01, 9.9000e+01],
        [7.4329e-01, 8.3839e-01, 7.0827e-01, 1.2148e-01, 6.5507e-01, 7.4329e-01,
         8.3839e-01, 7.0827e-01, 1.2148e-01, 6.5507e-01],
        [2.0483e-01, 8.5266e-01, 5.6404e-01, 5.0472e-01, 7.9405e-02, 2.0483e-01,
         8.5266e-01, 5.6404e-01, 5.0472e-01, 7.9405e-02],
        [3.6233e-01, 8.8175e-01, 6.5552e-01, 2.9521e-02, 6.6255e-01, 3.6233e-01,
         8.8175e-01, 6.5552e-01, 2.9521e-02, 6.6255e-01]])

In [36]:
# Multiplying

tensor = torch.rand(3,4)

print(tensor)
print(tensor.mul(tensor)) # Element-wise
# or
print(tensor * tensor)

tensor([[0.1532, 0.0982, 0.6616, 0.0600],
        [0.8824, 0.2273, 0.4693, 0.7808],
        [0.6570, 0.0172, 0.0271, 0.1944]])
tensor([[2.3479e-02, 9.6389e-03, 4.3773e-01, 3.6014e-03],
        [7.7870e-01, 5.1649e-02, 2.2024e-01, 6.0958e-01],
        [4.3162e-01, 2.9664e-04, 7.3657e-04, 3.7785e-02]])
tensor([[2.3479e-02, 9.6389e-03, 4.3773e-01, 3.6014e-03],
        [7.7870e-01, 5.1649e-02, 2.2024e-01, 6.0958e-01],
        [4.3162e-01, 2.9664e-04, 7.3657e-04, 3.7785e-02]])


In [37]:
print(tensor.matmul(tensor.T)) # Matrix Multiplication
# or
print(tensor @ tensor.T)

tensor([[0.4744, 0.5149, 0.1320],
        [0.5149, 1.6602, 0.7482],
        [0.1320, 0.7482, 0.4704]])
tensor([[0.4744, 0.5149, 0.1320],
        [0.5149, 1.6602, 0.7482],
        [0.1320, 0.7482, 0.4704]])


In [38]:
# In-place Operations, which will change the tensor

tensor = torch.randint(3,15,(4,4))
tensor

tensor([[ 9,  3, 13, 11],
        [13, 12,  9,  7],
        [ 3,  7, 11,  5],
        [11, 13, 13, 13]])

In [39]:
#Normal add operation
tensor.add(5)
print(tensor)

tensor([[ 9,  3, 13, 11],
        [13, 12,  9,  7],
        [ 3,  7, 11,  5],
        [11, 13, 13, 13]])


In [41]:
# Same tensor, now with in-place. '_' suffix is used for that
tensor.add_(5)
tensor

tensor([[14,  8, 18, 16],
        [18, 17, 14, 12],
        [ 8, 12, 16, 10],
        [16, 18, 18, 18]])

In [42]:
# Tensors on CPU and NumPy arrays can share their memory locations. If we change one, so will the other.
t = torch.ones(3)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1.])
[1. 1. 1.]


In [43]:
t.add_(3) #in-place
print(t)
print(n)

tensor([4., 4., 4.])
[4. 4. 4.]
