In [1]:
import torch
import numpy as np

In [2]:
print(torch.cuda.is_available())

True


In [3]:
torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

device(type='cuda')

In [4]:
torch_array = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
numpy_array = torch_array.numpy()

In [6]:
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(torch_array)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
np_array = np.array([[2,4],[3,6]])

In [9]:
tor_array = torch.tensor(np_array)

In [10]:
print(tor_array)

tensor([[2, 4],
        [3, 6]])


In [11]:
tensor = torch.rand(1,5,2,3)
print(tensor)

tensor([[[[0.6313, 0.4050, 0.7470],
          [0.9729, 0.1841, 0.6136]],

         [[0.9640, 0.9262, 0.4522],
          [0.8199, 0.8137, 0.4660]],

         [[0.3620, 0.5876, 0.2322],
          [0.0645, 0.1206, 0.7637]],

         [[0.7174, 0.3001, 0.3777],
          [0.8092, 0.8153, 0.1085]],

         [[0.4394, 0.4633, 0.5867],
          [0.0755, 0.0596, 0.2204]]]])


In [12]:
tensor_sq = tensor

In [13]:
squeezed_tensor = torch.squeeze(tensor_sq,dim=-4)
print(squeezed_tensor.shape)

torch.Size([5, 2, 3])


In [14]:
print(tensor_sq)

tensor([[[[0.6313, 0.4050, 0.7470],
          [0.9729, 0.1841, 0.6136]],

         [[0.9640, 0.9262, 0.4522],
          [0.8199, 0.8137, 0.4660]],

         [[0.3620, 0.5876, 0.2322],
          [0.0645, 0.1206, 0.7637]],

         [[0.7174, 0.3001, 0.3777],
          [0.8092, 0.8153, 0.1085]],

         [[0.4394, 0.4633, 0.5867],
          [0.0755, 0.0596, 0.2204]]]])


In [15]:
print(tensor_sq.sum(dim=1))

tensor([[[3.1140, 2.6823, 2.3958],
         [2.7420, 1.9933, 2.1723]]])


In [16]:
quiz_array = torch.tensor([[1, 2.2, 9.6],
                           [4, -7.2, 6.3]])

In [17]:
print(quiz_array.mean(dim=1))

tensor([4.2667, 1.0333])


In [18]:
x = torch.tensor([
                  [[2,6],[7,9]],
                  [[6,8],[26,23]],
                  [[34,25],[29,31]]])
print(x)

tensor([[[ 2,  6],
         [ 7,  9]],

        [[ 6,  8],
         [26, 23]],

        [[34, 25],
         [29, 31]]])


In [19]:
x.shape

torch.Size([3, 2, 2])

In [20]:
x[0].shape

torch.Size([2, 2])

In [21]:
x[:,0]

tensor([[ 2,  6],
        [ 6,  8],
        [34, 25]])

In [22]:
x[:,:,1:2]

tensor([[[ 6],
         [ 9]],

        [[ 8],
         [23]],

        [[25],
         [31]]])

In [23]:
matr = torch.arange(1,43).view(6,7)
matr

tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28],
        [29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42]])

In [24]:
y = torch.tensor([[1,2.2,9.6],[4,-7.2,6.3]])
y[:,0]

tensor([1., 4.])

In [25]:
y[:1]

tensor([[1.0000, 2.2000, 9.6000]])